source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodTest1618_Example', :exclusive => true do
  pod "PodTest1618", :path => "../"
end

target 'PodTest1618_Tests', :exclusive => true do
  pod "PodTest1618", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
